# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ad97cf58e2bccb5f48830b12ed7e5ec0"
name = "sne product discount"
handle = "sne-product-discount"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
